# -*- coding: utf-8 -*-
"""Ex_Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSoZURI5UZaazXa6o6SHLcFq0D3KEDZO
"""

#Este projeto é um exercício de Pandas para manipulação de dados para o setor de Dados da minha empresa
#No caso, foi utilizado um dataset com todos os goleiros que jogaram a Champions League 2020/2021

import pandas as pd

goleiros_df = pd.read_csv('ucl goalkeeper.csv')
display(goleiros_df)

goleiros_df = goleiros_df.drop('MP', axis=1)
goleiros_df = goleiros_df.drop('Starts', axis=1)
goleiros_df = goleiros_df.drop('Min', axis=1)
goleiros_df = goleiros_df.drop('90s', axis=1)
goleiros_df = goleiros_df.drop('CS', axis=1)
goleiros_df = goleiros_df.drop('CS%', axis=1)
goleiros_df = goleiros_df.drop('PKatt', axis=1)
goleiros_df = goleiros_df.drop('PKA', axis=1)
goleiros_df = goleiros_df.drop('PKsv', axis=1)
goleiros_df = goleiros_df.drop('PKm', axis=1)
display(goleiros_df)

goleiros_df = goleiros_df.dropna()
display(goleiros_df)

champions_df = goleiros_df[goleiros_df['Club'] == 'Manchester City']
display(champions_df)

goleiros_df.loc[:, 'Champion'] = 0
goleiros_df.loc[10, 'Champion'] = 1
display(goleiros_df)

display(goleiros_df.head(10))

brazucas_df = goleiros_df.loc[goleiros_df['Nationality'] == 'BRA']
display(brazucas_df)

# Criando uma coluna para indicar se o goleiro é brasileiro
goleiros_df.loc[:, 'Brazuca'] = 0

# Criando uma coluna para indicar se o goleiro é argentino
goleiros_df.loc[:, 'Argentino'] = 0